root: true
extends: "@samual/eslint-config"
parserOptions: { project: [ ./tsconfig.json, ./src/tsconfig.json ] }
ignorePatterns: [ examples, coverage ]
rules: { "@typescript-eslint/no-unused-vars": off }
